### ISSUE TITLE
Jail doesnt register multiple worlds (Multiverse)

### ISSUE THREAD

**Issue by ozzie2014** [graywolf336/Jail#100]
Couldn't find this issue online, but i have the jail plugin as well as the multiverse plugin, I'm creating a jail in one world, but it always teleports players to my original world. Is there a way to fix this or do the 2 plugins not work together?

**Comment by graywolf336** [comment]
Can you provide steps to reproduce it? And link me to the multiverse plugin? This way I can replicate what you're doing.

**Comment by ozzie2014** [comment]
http://dev.bukkit.org/bukkit-plugins/multiverse-core/
the steps are that described in the plugin, i create the jail, create the cells, and then i jail someone using all the commands in the plugin wiki and it takes them to my original world.

**Comment by graywolf336** [comment]
So, your jails aren't in the main world?

**Comment by ozzie2014** [comment]
no, their in another world

**Comment by graywolf336** [comment]
So, you have two worlds. The main world and a jail world (simplifying this
down). You then jail people in the jail world and they get sent to the main
world?

**Comment by ozzie2014** [comment]
it doesnt matter what location i am in it always sends them to the main world
