### ISSUE TITLE
PlayerMoveProtectionAction

### ISSUE THREAD

**Issue by Rhmul** [graywolf336/Jail#102]
I cant seem to find PlayerMoveProtectionAction in the plugin config in version 3.0.0

**Comment by graywolf336** [comment]
It's there: https://github.com/graywolf336/Jail/blob/master/src/main/resources/config.yml#L45

**Comment by Rhmul** [comment]
I cant find out to set it to the "escape" mode

**Comment by graywolf336** [comment]
Just disable the protection, by setting it to false.

**Comment by Rhmul** [comment]
But then they wont get their items back unto the jail time ends?

**Comment by Rhmul** [comment]
Is their a way that when they "escape" the jail they can get all their stuff bank and have their jail time removed?
