### ISSUE TITLE
jail only works 50% of the time

### ISSUE THREAD

**Issue by Ac3dUd3** [graywolf336/Jail#104]
as the title says, sometimes it works fine others when i turn my server on i get this. its on the latest version from you

```
09.01 18:31:58 [Server] INFO Enabling Jail v3.0.0-SNAPSHOT-b139
09.01 18:31:59 [Server] INFO Storage type selected: flatfile
09.01 18:31:59 [Server] INFO Loaded the language: en
09.01 18:31:59 [Server] INFO Loaded jail prison with 0 prisoners and 12 cells.
09.01 18:31:59 [Server] ERROR Error occurred while enabling Jail v3.0.0-SNAPSHOT-b139 (Is it up to date?)
09.01 18:31:59 [Server] INFO java.lang.IllegalArgumentException: Name cannot be null
09.01 18:31:59 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getWorld(CraftServer.java:1014) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at com.graywolf336.jail.JailIO.loadJailFromFlatFile(JailIO.java:604) ~[?:?]
09.01 18:31:59 [Server] INFO at com.graywolf336.jail.JailIO.loadJails(JailIO.java:578) ~[?:?]
09.01 18:31:59 [Server] INFO at com.graywolf336.jail.JailMain.onEnable(JailMain.java:77) ~[?:?]
09.01 18:31:59 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 18:31:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
09.01 18:31:59 [Server] INFO Enabling NoCheatPlus v3.13.4-BETA-sMD5NET-b901
```

**Comment by graywolf336** [comment]
Post your config.

**Comment by Ac3dUd3** [comment]
# ###################
# Jail v3.0.0-SNAPSHOT-b249 config file
# Note: You -must- use spaces instead of tabs!
# ###################
system:
  version: 3
  debug: false
  language: en
  updates:
    channel: bukkit
    notification: true
    time: 1h
  useBukkitTimer: true
storage:
  type: flatfile
  mysql:
    host: localhost
    port: 3306
    username: root
    password: password
    database: jailDatabase
    prefix: j3_
jailing:
  during:
    blockBreakPenalty: 5m
    blockBreakProtection: true
    blockBreakWhiteList:
    - crops
    - carrot
    - potato
    blockPlacePenalty: 5m
    blockPlaceProtection: true
    blockPlaceWhiteList:
    - crops
    - carrot
    - potato
    cellsign:
    - '%player%'
    - '%timeinminutes% mins'
    - with a reason
    - '%reason%'
    commandPenalty: 1m
    commandProtection: true
    commandWhitelist:
    - /ping
    - /list
    - /jail status
    - /jail pay
    countDownTimeWhileOffline: true
    cropTramplingPenalty: 5m
    cropTramplingProtection: true
    foodControl:
      enabled: true
      max: 20
      min: 10
    ignoreSleeping: true
    maxAFKTime: 10m
    movePenalty: 10m
    moveProtection: true
    openChest: true
    preventInteractionBlocks:
    - wooden_door
    - iron_door_block
    preventInteractionBlocksPenalty: 5m
    preventInteractionItems: []
    preventInteractionItemsPenalty: 5m
    recieveMessages: true
    scoreboard:
      enabled: false
      title: Jail Info
      time: '&aTime:'
  jail:
    allowJailingNeverPlayedBeforePlayers: false
    automaticCell: true
    automaticMute: true
    broadcastJailing: true
    clothing:
      enabled: true
      helmet: leather_helmet~175,105,33
      chest: leather_chestplate~175,105,33
      legs: leather_leggings~175,105,33
      boots: leather_boots~175,105,33
    commands: []
    default:
      jail: nearest
      time: 5m
    gameMode: adventure
    inventory:
      blacklist: []
      store: true
    log:
      console: true
      profile: true
  release:
    backToPreviousPosition: false
    commands: []
    restorePreviousGameMode: false
    teleport: true
jails:
  endermenProtection: true
  explosionProtection: true
jailpay:
  enabled: true
  item: air
  pricePerMinute: 1.5
  priceInfinite: 10000
jailstick:
  enabled: true
  sticks:
  - stick,30m,,Running away,-1
  - blaze_rod,15m,,Having too much fun,6
jailvote:
  enabled: true
  voteTimer: 60s
  minimumYes: 5
  reason: Jailed by players via Jail Vote
  time: 5m

**Comment by graywolf336** [comment]
And link to your jails.yml file.

**Comment by Ac3dUd3** [comment]
jails:
  prison:
    world: world
    top:
      x: -561
      y: 40
      z: -188
    bottom:
      x: -596
      y: 50
      z: -164
    tps:
      in:
        x: -595.5309971508019
        y: 45.0
        z: -174.72376268197493
        yaw: -93.0012
        pitch: 10.349958
      free:
        world: world
        x: 0.5
        y: 70.0
        z: 0.5
        yaw: -183.89992
        pitch: 26.099995
    cells:
      cell_n12:
        tp:
          x: -593.2174428771867
          y: 41.0
          z: -164.92222471504772
          yaw: 179.39716
          pitch: 5.7000413
        chest:
          x: -592
          y: 41
          z: -164
        signs:
        - world,-592.0,42.0,-167.0,0.0,0.0
      cell_n3:
        tp:
          x: -580.4463902307225
          y: 41.0
          z: -186.20402056644596
          yaw: 354.74857
          pitch: -6.29993
        chest:
          x: -582
          y: 41
          z: -188
        signs:
        - world,-582.0,42.0,-184.0,0.0,0.0
      cell_n6:
        tp:
          x: -562.5214334132986
          y: 41.0
          z: -185.8916773881991
          yaw: 355.648
          pitch: 2.2500443
        chest:
          x: -564
          y: 41
          z: -188
        signs:
        - world,-564.0,42.0,-184.0,0.0,0.0
      cell_n11:
        tp:
          x: -586.7083732140989
          y: 41.0
          z: -164.6993119565784
          yaw: 180.14716
          pitch: 4.8000274
        chest:
          x: -586
          y: 41
          z: -164
        signs:
        - world,-586.0,42.0,-167.0,0.0,0.0
      cell_n4:
        tp:
          x: -574.2053973185605
          y: 41.0
          z: -186.06865733532953
          yaw: 354.5985
          pitch: -3.599937
        chest:
          x: -576
          y: 41
          z: -188
        signs:
        - world,-576.0,42.0,-184.0,0.0,0.0
      cell_n8:
        tp:
          x: -569.0867426727871
          y: 41.0
          z: -165.0037729765266
          yaw: 172.79767
          pitch: 4.0500374
        chest:
          x: -568
          y: 41
          z: -164
        signs:
        - world,-568.0,42.0,-167.0,0.0,0.0
      cell_n9:
        tp:
          x: -574.9862942050726
          y: 41.0
          z: -164.40553239021168
          yaw: 178.49756
          pitch: 2.8500335
        chest:
          x: -574
          y: 41
          z: -164
        signs:
        - world,-574.0,42.0,-167.0,0.0,0.0
      cell_n2:
        tp:
          x: -586.3696324563201
          y: 41.0
          z: -186.03818313873597
          yaw: 351.59866
          pitch: -1.1999242
        chest:
          x: -588
          y: 41
          z: -188
        signs:
        - world,-588.0,42.0,-184.0,0.0,0.0
      cell_n10:
        tp:
          x: -580.8256878771311
          y: 41.0
          z: -164.19899024007768
          yaw: 172.64752
          pitch: 3.6000288
        chest:
          x: -580
          y: 41
          z: -164
        signs:
        - world,-580.0,42.0,-167.0,0.0,0.0
      cell_n7:
        tp:
          x: -563.1603260479305
          y: 41.0
          z: -164.5991550932078
          yaw: 178.34772
          pitch: 2.400044
        chest:
          x: -562
          y: 41
          z: -164
        signs:
        - world,-562.0,42.0,-167.0,0.0,0.0
      '001':
        tp:
          x: -592.3601134599343
          y: 41.0
          z: -186.21598394530065
          yaw: 356.54913
          pitch: 1.5000737
        chest:
          x: -594
          y: 41
          z: -188
        signs:
        - world,-594.0,42.0,-184.0,0.0,0.0
      cell_n5:
        tp:
          x: -567.9794844397563
          y: 41.0
          z: -186.18121102230992
          yaw: 357.14813
          pitch: 2.2500584
        chest:
          x: -570
          y: 41
          z: -188
        signs:
        - world,-570.0,42.0,-184.0,0.0,0.0
  prisoncells: {}

**Comment by graywolf336** [comment]
This was fixed in the newer versions. Just remove that last line `prisoncells: {}` and it'll be good to go.

**Comment by Ac3dUd3** [comment]
it says i am on build 249 but wants 182 when using plugman

**Comment by graywolf336** [comment]
I've never used plugman, so I can't help you there. Might need to do some research on that plugin then. But the issue which you've reported has been fixed in the newest builds, just remove the last line of the `data.yml` file.

**Comment by Ac3dUd3** [comment]
I did, Still crashing

**Comment by graywolf336** [comment]
Show the new error please.

**Comment by Ac3dUd3** [comment]
09.01 20:12:29 [Server] INFO Enabling Jail v3.0.0-SNAPSHOT-b253
09.01 20:12:29 [Server] WARN Loading the default language of: en
09.01 20:12:29 [Server] WARN If you wish to change this, please rename 'en.yml' to whatever you wish and set the config value to the name of the file.
09.01 20:12:29 [Server] ERROR Error occurred while enabling Jail v3.0.0-SNAPSHOT-b253 (Is it up to date?)
09.01 20:12:29 [Server] INFO java.lang.IllegalArgumentException: Stream cannot be null
09.01 20:12:29 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:207) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at com.graywolf336.jail.JailIO.loadLanguage(JailIO.java:69) ~[?:?]
09.01 20:12:29 [Server] INFO at com.graywolf336.jail.JailMain.onEnable(JailMain.java:75) ~[?:?]
09.01 20:12:29 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
09.01 20:12:29 [Server] INFO Enabling HolographicDisplays v2.1.10
09.01 20:12:29 [Server] INFO Found ProtocolLib, adding support for player relative variables.
09.01 20:12:29 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
09.01 20:12:29 [Server] WARN The author of this plugin has misconfigured the Updater system.
09.01 20:12:29 [Server] WARN The project ID (75097) provided for updating is invalid.
09.01 20:12:29 [Server] WARN Please notify the author of this error.
09.01 20:12:29 [Server] Startup Done (16.708s)! For help, type "help" or "?"
09.01 20:12:30 [Server] INFO ** Vaults have already been converted to UUIDs. If this is incorrect, shutdown your server and rename the plugins/PlayerVaults/uuidvaults directory.
09.01 20:12:30 [Server] INFO Added hook: AllViolations(NCP) [1.0].
09.01 20:12:30 [Server] INFO Added hook: mcMMO(cncp) [2.3].
09.01 20:12:30 [Server] INFO Metrics started: http://mcstats.org/plugin/PlugMan
09.01 20:12:30 [Server] INFO Post-enable running...
09.01 20:12:30 [Server] WARN The updater could not find any files for the project id 31030
09.01 20:12:30 [Server] INFO Post-enable finished.
09.01 20:12:30 [Server] INFO Searching for updates.
09.01 20:12:30 [Server] INFO Checking for Updates ... 
09.01 20:12:30 [Server] WARN The updater could not find any files for the project id 36006
09.01 20:12:30 [Server] WARN The project ID was invalid or could not be found.
09.01 20:12:30 [Server] INFO No update was found.
09.01 20:12:30 [Server] WARN No files found, or Feed URL is bad.
09.01 20:12:30 [Server] INFO No new version available
09.01 20:12:30 [Server] INFO Checking if conversion to UUID needed...
09.01 20:12:32 [Server] INFO No plot conversion needed
09.01 20:12:41 [Server] INFO UUID of player Ac3dUd3 is 73726a4c-e877-48da-9750-36bd02a09274
09.01 20:12:41 [Connect] User Ac3dUd3, IP 121.216.17.119
09.01 20:12:41 [Multicraft] Ac3dUd3 ran command Message of the Day
09.01 20:12:44 [Server] INFO Ac3dUd3 issued server command: /jail
09.01 20:12:44 [Server] ERROR null
09.01 20:12:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'jail' in plugin Jail v3.0.0-SNAPSHOT-b253
09.01 20:12:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
09.01 20:12:44 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
09.01 20:12:44 [Server] INFO Caused by: java.lang.NullPointerException
09.01 20:12:44 [Server] INFO at com.graywolf336.jail.enums.Lang.get(Lang.java:328) ~[?:?]
09.01 20:12:44 [Server] INFO at com.graywolf336.jail.enums.Lang.get(Lang.java:311) ~[?:?]
09.01 20:12:44 [Server] INFO at com.graywolf336.jail.JailMain.onCommand(JailMain.java:186) ~[?:?]
09.01 20:12:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot45.jar:git-Spigot-5f38d38-12698ea]
09.01 20:12:44 [Server] INFO ... 15 more

**Comment by graywolf336** [comment]
Okay, downgrade to https://ci.craftyn.com/job/Jail/246/. Then you'll be good to go.

**Comment by Ac3dUd3** [comment]
its working again :D thank you!

**Comment by graywolf336** [comment]
Glad to hear! :+1: Welcome
