### ISSUE TITLE
Inventory lost when unjailed

### ISSUE THREAD

**Issue by astr1al** [graywolf336/Jail#109]
With the Jail 3.0.0 versions, players are losing their inventory when being released from jail. I've set inventory store to true and false with the same results. Even tried disabling gamemode change on unjail without much luck. Player's are able to keep their current inv in jail but lose it when released. Didn't see a ticket about it so thought I'd pass it on. 

Running on spigot version 1.8.8 R0.1-Snapshot
Config: http://pastebin.com/drtRR4Kr

I do run multiverse inventories, but my jail is in the main world, so it shouldn't be affecting it?

**Comment by djlawrence4** [comment]
Did the jailed take his items out of the chest?  I noticed that when I tested the plugin if the jailed removes his items from his chest to his inventory he will lose all of his items.  So what I did was created another room just for chests and then assigned them based on the room and blocked off access from the chests so their items will be secured.
