### ISSUE TITLE
Signs don't work after reload plugin

### ISSUE THREAD

**Issue by tonyZxD** [graywolf336/Jail#111]
After reload plugin with /jail reload or server restart signs don't work. On data.yml '_signs_:' form is empty. Before restart, in data.yml under the sign exist positions for sign. I don't know why disappear.

**Comment by graywolf336** [comment]
What versions of Jail and Spigot?

**Comment by graywolf336** [comment]
@tonyZxD Can you test with Build 259 and let me know if it still exists there? https://ci.craftyn.com/job/Jail/259/

**Comment by graywolf336** [comment]
Closing, as this might have been fixed a while back and I just tested it to verify the issue was fixed.
