### ISSUE TITLE
Unjailing a Player does not fully Unjail and give inventory back.

### ISSUE THREAD

**Issue by ninmore** [graywolf336/Jail#112]
So in my config I have keep inventory enabled, but when you Unjail a player it will teleport them, but it will not give their inventory back and also they are still marked as jailed and still stored on the Jailed players database.

It will also throw this error: http://bit.ly/1PiyOCn 

The only way to fix this is to remove the player from the database but they will never get their inventory back. Also please update the source code here, I would try and help to see what the problem is but the code is out of date.

Cheers

**Comment by graywolf336** [comment]
What versions of Jail and Spigot?

**Comment by ninmore** [comment]
Jail 3.0.0 and the latest build of Spigot 1.9-dev

**Comment by graywolf336** [comment]
Are they jailed in a cell? If so, does that cell have a chest associated with it?

**Comment by graywolf336** [comment]
So, the issue seems to be coming from the addition of the left hand slot.

**Comment by ninmore** [comment]
There are no cells, in the jail that I used.

**Comment by graywolf336** [comment]
@ninmore Let's try now with [build 261](https://ci2.craftyn.com/job/Jail/261/), let me know how it works.

**Comment by ninmore** [comment]
@graywolf336 Looks all good from here, jailing works, no more inventory errors. Also creating a jail now works correctly, with nothing glitching out with multiple selections happening at the same time.

**Comment by graywolf336** [comment]
:+1: thanks for reporting back!
