### ISSUE TITLE
Duplicating Gear

### ISSUE THREAD

**Issue by djlawrence4** [graywolf336/Jail#113]
When i jail a player and then unjail them... their gear duplicates into their inventory

**Comment by graywolf336** [comment]
What versions of Jail and Spigot?

**Comment by djlawrence4** [comment]
I am running Jail v3.0.0 (Build#182) and latest Spigot 1.9 build

**Comment by graywolf336** [comment]
Okay, let's get you updated to build 259, https://ci.craftyn.com/job/Jail/259/, and then let me know if the issue still exists.

**Comment by djlawrence4** [comment]
Ok I tested the new build and duplicating gear still occurs
