### ISSUE TITLE
Impossible to create a jail.

### ISSUE THREAD

**Issue by morsay** [graywolf336/Jail#114]
Hi im using 1.9 version of minecraft and when i create a jail then right click on the first point one time it select 2 points in same time , so i cant do anything, ssry for my bad english.

**Comment by ninmore** [comment]
Yeah this started happening in 1.9. With debugging enabled, it will sometimes register a single right click 3 times.

**Comment by morsay** [comment]
So what i need to do ?

**Comment by ninmore** [comment]
There is nothing much you can do, try making a jail with an old version of jail then upgrading jail again.

**Comment by graywolf336** [comment]
Interesting, wonder what the change was which is triggering this. If anyone finds it, feel free to submit a pull request.

**Comment by graywolf336** [comment]
Did some research, and this is a bug with Spigot currently. I will add a workaround, albeit I'm not happy about it.

**Comment by graywolf336** [comment]
Build 259 contains the fix for it (https://ci.craftyn.com/job/Jail/259/).

**Comment by xIPad3Zockerx** [comment]
It's the second hand in minecraft lel
