### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Eichi92** [graywolf336/Jail#116]
Hi
Thanks for Insert #110  :)

But I have another problem
I get this error when a player placed blocks

http://pastebin.com/53PrFGLa

I have tested various versions of spigot (1.8)
I currently use
"This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)"

Sorry for that bad "Google Translator English"

**Comment by graywolf336** [comment]
Recent versions of Jail are only working with 1.9 due to required changes for inventory management which 1.9 forced us to make. If 1.8 support is required, it will cause a split in feature support and a higher maintenance cost.

**Comment by Eichi92** [comment]
Okay thanks :)
