### ISSUE TITLE
Tab-Completion Doesn't With /jail [name]

### ISSUE THREAD

**Issue by Verden1992** [graywolf336/Jail#117]
Hello,

first: cool Update with UUIDs :)

Jail Record works perfect now!

But i find anotther bug.

If you jail somenone with /jail [name] -t -r etc. the autorefill with tab doenst work anymore with the new update :/

With the older version it already works with autorefill.

Also strange: if you use /unjail [name] the autorefill works fine.

So i hope its only a small bug and you can fix it fast :)

Greetings from Germany

André

**Comment by graywolf336** [comment]
I changed the title to something which makes more sense, but I will see what the issue is later this week.

**Comment by Verden1992** [comment]
Hi,

ist it solved in the latest build? :)

**Comment by graywolf336** [comment]
@Verden1992 It is now 👍
