### ISSUE TITLE
Player lost inventory whilst jailed, could you translate the code

### ISSUE THREAD

**Issue by ThemInspectors** [graywolf336/Jail#119]
So Someone was jailed when there was no cells & they lost their inventory & alot since i didn't have any chests it started complaining I have his data kept safe so could you decode it?

http://pastebin.com/e7D9gnh7

**Comment by graywolf336** [comment]
That can only be decoded by the plugin. You'll have to do some extra work
to get it back to him, I don't have the steps on hand.
