### ISSUE TITLE
Jailstick Permissions

### ISSUE THREAD

**Issue by Curtis73** [graywolf336/Jail#123]
Hi, I have a small issue with my jail stick permissions.
The police have all the right perms (jail.usejailstick.180) etc, and the criminals have jail.canbestickjailed - but for some reason, the police can only jail the criminals if they are OP. I have tried giving them "*"  perms, but it won't work. Do you know why this is? I am running 1.8.9.

Thanks :)

**Comment by graywolf336** [comment]
You need to give them `jail.usejailstick.material_name` instead of the number.

**Comment by Curtis73** [comment]
Thanks!
