### ISSUE TITLE
Armor doesnt restore if unjail someone

### ISSUE THREAD

**Issue by Verden1992** [graywolf336/Jail#124]
Hello,

next build, next Bug ^^

If you jail someone with armor (not in inventory, wear it) and than unjail him, the armor he weared ist not restored. All other items are restored. But not the Armor.

I hope you can fix it quick :)

**Comment by graywolf336** [comment]
What version are you using of Bukkit?

**Comment by Verden1992** [comment]
1.8.9

**Comment by graywolf336** [comment]
Are you using the build for 1.8?
https://ci.craftyn.com/job/Jail%20-%20Bukkit%201.8/

**Comment by Verden1992** [comment]
Hello,

i tested this build: https://ci.craftyn.com/job/Jail%20-%20Bukkit%201.8/ an it doesn't work. Armor ist not restored.

Here is my config:
http://pastebin.com/PJeXgHwL

**Comment by Geirrathr** [comment]
I have the same problem using Spigot 1.8.8 and Jail 3.0.0.1.8-SNAPSHOT-b9

**Comment by graywolf336** [comment]
1.8.x is no longer supported.
