### ISSUE TITLE
Prisoner tags in command in config.yml doesn't work 

### ISSUE THREAD

**Issue by novrom** [graywolf336/Jail#126]
In config.yml in jail: and release: has a setting commands: []

I insert command to another group when arrested
- pex user < Player> group set Banned

command work, but not to transfer the player, and transferred nickname < Player>

[Prisoner tags](http://dev.bukkit.org/bukkit-plugins/jail/pages/prisoner-tags/) not work

I'm use Jail 3.0.0 b182, Spigot 1.8.8 and PermissionsEx 1.23.4

**Comment by Lolmaster25** [comment]
That's because < Player > isn't the tag but %p% or %player% is
