### ISSUE TITLE
Translate dont work!

### ISSUE THREAD

**Issue by peppemax9** [graywolf336/Jail#127]
Hi, i try for 2H at change lang at plugin but when i save file and start server, the old translate return and regen old file en.yml, i try all!! PLS HELP ME!
(sorry for my bad eng, im italian)

**Comment by peppemax9** [comment]
Up!

**Comment by Lolmaster25** [comment]
Mi sa che qualcuno deve fare la traduzione di tutto il file "en.yml" e crearne uno nuovo "it.yml". Se c'è richiesta lo potrei fare io.

**Comment by graywolf336** [comment]
I was able to get it working earlier..make sure your file is named and you change the setting in the config to read from it.
