### ISSUE TITLE
Weird Bugs?

### ISSUE THREAD

**Issue by Subby72** [graywolf336/Jail#133]
Can you PLEASE help. The /jail command to send someone to jail doesn't work at all. The jailsticks seem to work only when they want to, and I can't determine what conditions have to be set for them to work. Also, the jailsticks never work if the player is in claimed land (GriefPrevention) or have /fly enabled. Some of our players have this ability in survival. I think the plugin may be conflicting with Essentials and its /jail commands. I went into Essentials config file and added /jail to the overwritten command list and even tried adding it to the disabled commands list. Neither one helped. Please, someone help me get the configurations correct. The players on my server LOVE this plug-in.

Also, the jail guards do not spawn...

**Comment by graywolf336** [comment]
Sounds like an extreme conflict with essentails jail module. Try to disable it and this plugin should work right.
