### ISSUE TITLE
Player Jailed; Items Not Going Into Chest.

### ISSUE THREAD

**Issue by TheProdigalGoat** [graywolf336/Jail#134]
Issue: The items in a player's inventory are not going into the chest (marked in the config file [config.yml]).
Plugin Version: Latest (Version 3.0.0 [Snapshot, Build 268])

Issue Extended:
Whenever my friend and I build the jail cells using this plugin, we are asked to set the chest for all of the player's items to go into when they are jailed. This has not started happening until quite recently, furthermore, it is extremely irritating as the cells and chests are unlinked when the server is stopped and / or restarted, therefore leading to all of the cells being recreated again. I understand that this plugin is in Snapshot mode, but it is still really irritating...

When did this start happening:
In the last few days, all my friend and I can gather so far is that the cells and their chests are unlinked virtually when the server is restarted or stopped, however, the data remains in the data.yml file.

How this issue affects us & our server:
This issue is a major one as we have 1000 cells in a 10 level prison, and we cannot afford to rebuild all of the cells again.

Any Extra Information:
- Even though /jail reload succeeds (or at least according to the chat) yet none of the cells are actually reloaded / re-instated.

**Comment by graywolf336** [comment]
Version of Minecraft?

**Comment by TheProdigalGoat** [comment]
Hey graywold336,

Sorry about the late response, I was out of the house all day and only just got back, anyway, I am using Minecraft version 1.10.2

**Comment by graywolf336** [comment]
Closing as I verified that cells don't lose their assigned chests when using flatfile (I can't test mysql yet).
