### ISSUE TITLE
No commands to create a jail

### ISSUE THREAD

**Issue by masterstreamer** [graywolf336/Jail#135]
The /jailcreate and the other commands are "unknown commands", if I type /help jail it says

```
Below is a list of all Jail commands:
/handcuff: Allows the player to handcuff another player
/jail: Jail specified player for specified amount of time.
/togglejaildebug: Toggles whether the plugin is in debugging state or not.
/unhandcuff: Allows the player to unhandcuff someone
/unjail: Release a player from jail.
/unjailforce: Remove player from the database.
```
That was all, so I can't create a jail. In debug mode there is no error, even without debug mode.
Thanks for helping.

**Comment by colajunkie13** [comment]
I guess you are using jail 3.0? I believe 3.0 is still in beta and the commands are getting a complete overhaul.
You can find the new commands here:

**Comment by masterstreamer** [comment]
So only the blue commands will work?

**Comment by colajunkie13** [comment]
No. The difference is this:
Old Jail create command: `/jailcreate` + arguments
New Jail create command: `/jail create` + arguments

**Comment by graywolf336** [comment]
Would love for someone to submit a pull request and add a `/jail help` along with a `/jailhelp` command.
