### ISSUE TITLE
Bug: Jail Zone Creation

### ISSUE THREAD

**Issue by Lolmaster25** [graywolf336/Jail#139]
I'm using the verison 3.0.0, in mc 1.8.8.
When I go to create a jail i do the first 3 steps (first point, second point, telein point) perfectly but when i go to select the teleout point this error comes in chat:

---------- Jail Zone Creation ----------
Teleport out point NOT selected. Go outside of the jail and
right click anywhere to select your current position as the
location where people will be teleported after ther are
released from this jail.
------------------------------------------------

I have tried multiple times, without success. Is there a minimum distance between the telein and teleout points? I love this plugin and this has never happended before. Please help!

**Comment by graywolf336** [comment]
The teleport out location must be **outside** the jail's zone.

**Comment by Lolmaster25** [comment]
can it be in another world?

**Comment by graywolf336** [comment]
I think so

**Comment by Lolmaster25** [comment]
it worked, thanks a lot @graywolf336!

**Comment by graywolf336** [comment]
:+1:
