### ISSUE TITLE
Cell names

### ISSUE THREAD

**Issue by Lolmaster25** [graywolf336/Jail#144]
When I create cells in my prison it automatically names them cell_n[x]. Is ther anyway to change the cell name, I've even tried to change it from a data file but then the plugin changes the names back. Is it in any way possible?

**Comment by graywolf336** [comment]
Get it figured out?

**Comment by Lolmaster25** [comment]
yep, that's why I closed it

**Comment by Lolmaster25** [comment]
and I've opened anotherone for a different problem, can you please go and check #145
