### ISSUE TITLE
Mysql error -plugin off

### ISSUE THREAD

**Issue by BabelSolea** [graywolf336/Jail#147]
![image](https://cloud.githubusercontent.com/assets/23665302/22224564/234f002a-e1d0-11e6-9f26-9f13b7d047ef.png)
![image](https://cloud.githubusercontent.com/assets/23665302/22224609/48baf6a2-e1d0-11e6-9e54-6a79ae56d06d.png)
why mysql not working?
that error 100%
i using mysql same settings in more then 10 plugins and that first time when have that error

Access denied for user 'ua1346e'@'localhost' to database 'jailDatabase' ???

how that can be possible????

and one more question - how  i can create any jail with new plugin version from Jenkins build with out command like jail create? (i was think what i will get default tables in mysql and configure jails here, but that error.... fantastic)

spigot 1.11.2
Jail-3.0.0-SNAPSHOT.jar (vault protocollib and others have installed) #278 build

**Comment by BabelSolea** [comment]
i maked another way:

i dont know what did really help me.

1. i choose old mysql info:
database: minecraft
prefix: jail_

2. i upload addicionally original-Jail-3.0.0-SNAPSHOT.jar #278 in plugin folder

then reload server. jail didnt show errors now.
i dont know why that fukin work look like that:

pls look that video! that really show like developing minecraft and her plugins
https://vk.com/stepanovia?z=video4899516_456239088%2Fd0744c6ecce59ed99a%2Fpl_wall_7923957

**Comment by graywolf336** [comment]
Closing because this is a permissions issue, you didn't grant the correct permissions in mysql for the user and the table/database.
