### ISSUE TITLE
Jail Swear Issue and inventory issue

### ISSUE THREAD

**Issue by dkiller11** [graywolf336/Jail#148]
Hi, 

I have Jail Swear: Enabled: set to true but for some reason it only puts players in jail when they say a banned word with another character after for example "**** y" would send them to jail but just "****" would not, so if they only say the swear word it doesn't send them to jail, any ideas?

Also when i use "/jail dev 5 mainjail:Cell1 reason" it takes their inventory and stores it in the chest but when they are jailed for saying a banned word it does not store their inventory in the just, so once they are unjailed their items are gone. 

Many thanks
Dkiller

**Comment by graywolf336** [comment]
Jail swear is not part of the v3 version yet, at least I don't see any settings for it. As a result, closing this issue.
