### ISSUE TITLE
Console Error on Load - Need 1.12 update.

### ISSUE THREAD

**Issue by LordDWT** [graywolf336/Jail#155]
Issue:
https://ghostbin.com/paste/7rr3h

Version:
CraftBukkit version git-Spigot-b78586d-2585751 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

Plugins (32): CoreProtect, dynmap, WorldEdit, Essentials, Trading, LWC, Multiverse-Core, ProtocolLib, WorldGuard, NoCheatPlus, Shopkeepers, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, PermissionsEx, WGCustomFlags, Multiverse-Portals, EssentialsSpawn, GriefPrevention, PvPManager, BetterAlias, PvEManager, Orebfuscator4, AntiXRay, Dynmap-Essentials, AuthMe, Dynmap-WorldGuard, Jail, Magic, Multiverse-NetherPortals, JDynmapGriefPrevention, MobArena

Version jail:
Jail version 3.0.0-SNAPSHOT-b268
Ban too harsh? Kick/mute/whatever not enough? Jail bad players!
Website: dev.bukkit.org/server-mods/jail/
Author: graywolf336

**Comment by LordDWT** [comment]
Still need update.

**Comment by graywolf336** [comment]
Done
