### ISSUE TITLE
Creating jail doesnt work

### ISSUE THREAD

**Issue by Keikeo91** [graywolf336/Jail#156]
Curious if you will be updating your Jail plugin to work with the newest version on MC. It was a very popular plugin and I think a lot of people would be very happy if you did so. As it stands right now, it is broke when in the process of creating a jail. It lets you select a first point for the cuboid but will not let you select a second. I hope you'd consider looking into this and good luck!

-Keikeo91

**Comment by graywolf336** [comment]
Please search through the issue of the issues, that has been fixed and issues closed time and time again.
