### ISSUE TITLE
Errors with spigot 1.12.2 version, no jail created

### ISSUE THREAD

**Issue by AngieC233** [graywolf336/Jail#161]
Using this Jail v3.0.0-SNAPSHOT-b281 and running CraftBukkit version git-Spigot-109b080-ab09b27 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

No jail shown even though it was created. It was work fine a few spigot version before, can't remember which version though.

Hopefully, this can be resolved. Thank you @graywolf336! 

Errors spamming here....
https://pastebin.com/Ti2UP9aE

**Comment by graywolf336** [comment]
Closing as there are new builds available and with those, I was able to create a jail, and cells, on the latest Bukkit version.
