### ISSUE TITLE
/jailcreate not working 

### ISSUE THREAD

**Issue by drlittle1** [graywolf336/Jail#166]
29.05 23:45:42 [Server] INFO Drelittle issued server command: /jail:jailcreate jail
29.05 23:45:42 [Server] ERROR null
29.05 23:45:42 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'jail:jailcreate' in plugin Jail v2.6.5-b3
29.05 23:45:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
29.05 23:45:42 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
29.05 23:45:42 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.contains(I)Z
29.05 23:45:42 [Server] INFO at com.matejdro.bukkit.jail.JailZoneCreation.selectstart(JailZoneCreation.java:20) ~[?:?]
29.05 23:45:42 [Server] INFO at com.matejdro.bukkit.jail.commands.JailCreateCommand.run(JailCreateCommand.java:24) ~[?:?]
29.05 23:45:42 [Server] INFO at com.matejdro.bukkit.jail.commands.BaseCommand.execute(BaseCommand.java:30) ~[?:?]
29.05 23:45:42 [Server] INFO at com.matejdro.bukkit.jail.Jail.onCommand(Jail.java:214) ~[?:?]
29.05 23:45:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1.13.2.jar:git-Spigot-1a3504a-dfa7583]
29.05 23:45:42 [Server] INFO ... 15 more

**Comment by graywolf336** [comment]
That's an extremely old version of the plugin, please update: https://ci.craftyn.com/job/Jail/
