### ISSUE TITLE
Time formatting

### ISSUE THREAD

**Issue by J0sch** [graywolf336/Jail#35]
It would be nice if the displayed jailtime (Sign, Scoreboard) can be formatted like this:
1d2h15m

**Comment by graywolf336** [comment]
Added for the signs, scoreboards won't have it for right now..need to figure out how I want to accomplish that. But for signs, the text `%prettytime%` will be replaced with something like `1d0h3m17s`.

**Comment by J0sch** [comment]
Thank you! :)
