### ISSUE TITLE
Could not create jail

### ISSUE THREAD

**Issue by henryhwilson** [graywolf336/Jail#37]
No /createjail function exists (in fact, only /handcuff, /unhandcuff, and /jail are provided). Running CB 1.8

**Comment by graywolf336** [comment]
They have been moved, as was stated on the download page on [Bukkit Dev](http://dev.bukkit.org/bukkit-plugins/jail/files/40-jail-v3-0-0/): `Command system has changed drastically. Every command that used to be together is now separate. Please see this page for information.` And the page it links to is: https://github.com/graywolf336/Jail/wiki/Commands
