### ISSUE TITLE
Add Auto Cell Selection Back on Jail

### ISSUE THREAD

**Issue by madisonofccs** [graywolf336/Jail#42]
When I used /jail [username] on a player, the player was assigned a cell and teleported to it, rather the prisoner was teleported to the main teleport point for the jail instead.

Using Build #160.

**Comment by graywolf336** [comment]
Please list the full command which you did.

**Comment by madisonofccs** [comment]
if the user being jailed was named foo, it would be /jail foo. There were no other additional parameters. When I had this plugin before, that was all it took to jail someone. If the jail had cells it automatically put the prisoner into a cell.

**Comment by graywolf336** [comment]
Interesting, I don't remember seeing that specific logic in the code. I just looked and you're correct, it did actually do that: https://github.com/multidude/Jail/blob/bug-fixes/src/com/matejdro/bukkit/jail/PrisonerManager.java#L103

Maybe retitle this issue to something like `Add Auto Cell Selection Back on Jail`, that way it is more descriptive as to what needs to happen?
