### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by kuzonov98** [graywolf336/Jail#43]
Hi! Do you need translate to Russian? It's allready done!

Messages:
  MessageJail: Вас отправили в тюрьму!
  MessageJailReason: 'Вас отправили в тюрьму! Причина: <Reason>'
  MessageUnJail: Вас выпустили из тюрьмы! Пожалуйста, соблюдайте правила сервера.
  PlayerNotJailed: Игрок не в тюрьме!
  PlayerAlreadyJailed: Этот игрок уже в тюрьме!
  MessageYouNotJailed: Вы не в тюрьме!
  BlockDestroyedNoPenalty: Не ломайте тюрьму!
  BlockDestroyedPenalty: Не ломайте тюрьму! Дополнительно, Вы остаётесь в тюрьме на 30 минут!
  MessageEscapeNoPenalty: Не пытайтесь сбежать!
  MessageEscapePenalty: Не пытайтесь сбежать! Дополнительно, Вы остаётесь в тюрьме на 30 минут!
  MessageBlockPlacedNoPenalty: Не ставьте блоки в тюрьме!
  MessageBlockPlacedPenalty: Не ставьте блоки в тюрьме! Дополнительно, Вы остаётесь в тюрьме на 30 минут!
  ForbiddenCommandNoPenalty: Не пытайтесь сбежать при помощи команд!
  ForbiddenCommandPenalty: Не пытайтесь сбежать при помощи команд! Дополнительно, Вы остаётесь в тюрьме на 30 минут!
  ForbiddenTransfer: Вас перевели в другую тюрьму!
  MessageMuted: Перестать разговаривать! Жди молча своего освобождения
  PreventedInteractionNoPenalty: Не делай этого!
  PreventedInteractionPenalty: Не делай этого!  Дополнительно, Вы остаётесь в тюрьме на 20 минут!
  MessageAFKKick: Нельзя находиться AFK!
  MessageJailPayAmountForever: Чтобы выйти под залог, вы должны оплатить <Amount>.
  JailPayCannotPay: Изивни, деньги в этот раз тебе не помогут.
  JailPayCannotPayHim: Изивни, деньги в этот раз ему не помогут.
  JailPayNotEnoughMoney: У тебя нет таких денег!
  JailPayNotEnoughMoneySelected: Этого будет не достаточно, чтобы 
  JailPayCost: 1 минута заточения здесь будет стоить <MinutePrice>. Таким образом, вполная стоимость за освобождение будет <WholePrice>.
  JailPayPaidReleased: Ты только что оплатил <Amount> и спас себя от тюрьмы!
  JailPayPaidReleasedHim: Ты только что оплатил <Amount> и спас себя <Prisoner> от тюрьмы!
  JailPayLoweredTime: Ты только что оплатил <Amount> и уменьшил срок до <NewTime> минут!
  JailPayLoweredTimeHim: Ты только что оплатил <Amount> и уменьшил срок <Prisoner> до <NewTime> минут!
  TimeMinutes: <Time> минут
  Forever: всегда
  JailStatus: <Jailer> отправил тебя в тюрьму на <TimeS>!
  JailStatusReason: <Jailer> отправил тебя в тюрьму на <TimeS> по причине <Reason>
  JailCheckLine: <Player> - в тюрьме на <TimeS> в <Jail>
  MessageJailCheckLineWaitingOffline: <Player> - Ждём первого захода на сервер
  JailStickEnabled: JailStick включена!
  JailStickDisabled: JailStick выключена!
  NoJail: Нет ни одной тюрьмы. Сначала постройте её, прежде чем сажать кого-нибудь!
  NeverOnThisServer: Игрок <Player> не был на этом сервере!
  TooLongReason: Слишком длинная причина!
  PrisonerJailed: Игрок <Player> отправлен в тюрьму.
  PrisonerOffline: Игрок <Player> оффлайн. Он отправится в тюрьму при первом ж заходе на сервер.
  Escape: <Player> сбежал из тюрьмы!

**Comment by kuzonov98** [comment]
And few words

Jail Vote:
  Enabled: true
  Time: 10
  Reason: По желанию игроков

**Comment by graywolf336** [comment]
Thanks for this, sadly those are the old messages for the old version of
the plugin. Here is the english language file for the new version:
https://github.com/graywolf336/Jail/blob/master/src/main/resources/en.yml
if you still feel up to translating it, that would be awesome!

Thanks

**Comment by graywolf336** [comment]
@kuzonov98 Any chance you can translate the new language file linked above?

**Comment by kuzonov98** [comment]
Yes. I'm just seek too much and can't use my laptop to translate. As soon
as I feel better I'll translate

**Comment by graywolf336** [comment]
Get well soon! Thanks, looking forward to the translation.

**Comment by graywolf336** [comment]
@kuzonov98 Are you still interested in translating the newest version?

**Comment by kuzonov98** [comment]
Hi. Yes. I had many problems and exmas, but now I can try.

**Comment by graywolf336** [comment]
If you don't mind, I'm trying out this website https://poeditor.com/join/project/zK1CT5cash for all the translations. I have updated all the things which need to be translated there, feel free to start it. :smile:

**Comment by kuzonov98** [comment]
Hello! I've finished translation! But i'm confused by one phrase "A player
context is required for this". Can you explain it to me?

чт, 18 июня 2015 г. в 1:38, graywolf336 <notifications@github.com>:

**Comment by graywolf336** [comment]
Awesome! That message is sent to the console or command blocks when they
try to do a command which only a player can do. That make more sense?

**Comment by kuzonov98** [comment]
Yeap. That's all. I'm done. If there are some mistakes text me. I'll
correct. Good luck with your project! :)
P.S. Can you please still support 1.7.10 beacuse not all plugins updated to
1.8?

пн, 13 июля 2015 г. в 0:16, graywolf336 <notifications@github.com>:

> Awesome! That message is sent to the console or command blocks when they
> try to do a command which only a player can do. That make more sense?

**Comment by graywolf336** [comment]
I will let you know if we add any more phrases as well, since there will be
some in the coming weeks.

As far as I know, 1.7 is still supported. But if it isn't, let me know..

**Comment by kuzonov98** [comment]
Jail 3.0.0 is only for 1.8.1 so I have to use v2.6.5




Dne st 15. 7. 2015 0:53 uživatel graywolf336 <notifications@github.com>
napsal:

> I will let you know if we add any more phrases as well, since there will be
> some in the coming weeks.
>
> As far as I know, 1.7 is still supported. But if it isn't, let me know..
>
> On Tue, Jul 14, 2015 at 4:45 PM, kuzonov98 <notifications@github.com>
> wrote:
>
> > Yeap. That's all. I'm done. If there are some mistakes text me. I'll
> > correct. Good luck with your project! :)
> > P.S. Can you please still support 1.7.10 beacuse not all plugins updated
> to
> > 1.8?
> >
> > пн, 13 июля 2015 г. в 0:16, graywolf336 <notifications@github.com>:
> >
> > > Awesome! That message is sent to the console or command blocks when
> they
> > > try to do a command which only a player can do. That make more sense?

**Comment by graywolf336** [comment]
Have you even tried Jail 3.0.0 on a 1.7 environment? If so, what errors are
there?

**Comment by kuzonov98** [comment]
Oh. Ok. 3.0.0. works fine o 1.7.10. I just though that that's only for
1.8.1. I think that you can write about it in head or somewhere in visible
place so users can install it without any doubts. Anyway thank you very
much for advise.

ср, 15 июля 2015 г. в 1:18, graywolf336 <notifications@github.com>:

**Comment by graywolf336** [comment]
Well, i haven't tested to see if it worked or not so if you run into
problems be sure to report them. After i test it with 1.7.10 I'll put it
up. :)

**Comment by miketorman** [comment]
If you need I can translate to Spanish, Portuguese, German, Swedish, and Japanese. 
I don't personally speak these languages but I have employees that do and id be more than happy to dispatch them for you if you could solve my problem with region selection. Feel free to email me at Admin@OtaconWeb.Com

Thanks.

**Comment by graywolf336** [comment]
Closing this now. If you would like to help translate, please let me know and I'll invite you to our new translation service.
