### ISSUE TITLE
Signs aren't being "updated" ?

### ISSUE THREAD

**Issue by lowheartrate** [graywolf336/Jail#44]
When I went to test the plugin and jailed someone the signs that were connected to each jail would not anything that it should have. The only thing that is worded on the sign is the same thing as it has before I jailed someone which is, "Empty Cell". Hope that someone can help me out on fixing this or in the future be fixed in another update?
![2015-02-02_17 25 31](https://cloud.githubusercontent.com/assets/8846438/6010459/86ff2626-ab00-11e4-95c8-9c1dbdf9a8a9.png)

<a href="http://pastebin.com/m91NkWxV">here</a> is a pastebin of my config file. 
Best regards,
Codi

**Comment by graywolf336** [comment]
Which version of the plugin, like which build? What server version?

On Mon, Feb 2, 2015 at 4:25 PM, Codi Bezouka-Smith <notifications@github.com

**Comment by madisonofccs** [comment]
sounds like the problem might be tied to #42. since cells aren't being assigned a prisoner, the signs don't update.

**Comment by graywolf336** [comment]
So, are you actually jailing them into cells or what command are you doing?

**Comment by madisonofccs** [comment]
i'm not sure what the OP is doing, but I'm just doing the general jail command, I'm not sure how to jail to a specific cell.

**Comment by graywolf336** [comment]
Take a look here: https://github.com/graywolf336/Jail/wiki/Jail-Command#first-example

**Comment by graywolf336** [comment]
Or take a look at the third example, with the `-a` which selects any cell available.

**Comment by madisonofccs** [comment]
I'll try that and see if I can confirm what the OP is talking about

**Comment by graywolf336** [comment]
Just verified on my server with build 166 that the signs do update when you actually do jail someone in a cell with a sign attached, see the [Jail Command Wiki Page]( https://github.com/graywolf336/Jail/wiki/Jail-Command) for how to Jail in a cell.

**Comment by madisonofccs** [comment]
ah, your faster than I am :)

**Comment by madisonofccs** [comment]
but now I know of the -a switch, so at least I can use that until the auto cell select is in

**Comment by graywolf336** [comment]
Go ahead and try to replicate it and then if the issue shows up for you I can reopen it.

**Comment by madisonofccs** [comment]
works fine for me on my end too, build 166. Looks like its all good.
