### ISSUE TITLE
Infinite time?

### ISSUE THREAD

**Issue by stingerbee12** [graywolf336/Jail#49]
How do you format the time (-t) when doing forever? (Infinite time so there is no expiration date)

**Comment by graywolf336** [comment]
Try to jail them with `-1` as the time, see if that works?

**Comment by stingerbee12** [comment]
@graywolf336 Yeah I get unexpected option and some other bunch of red errors.

**Comment by graywolf336** [comment]
Heh okay, then I'll look into it.

**Comment by stingerbee12** [comment]
Okay thanks

**Comment by stingerbee12** [comment]
So any idea? @graywolf336

**Comment by graywolf336** [comment]
Not yet, @stingerbee12. I will check it out tomorrow, working on adding the Jail Vote feature back in first as I've been slowly working on it.

**Comment by graywolf336** [comment]
@stingerbee12 Latest build you can now include `-i` anywhere in the command and it will jail someone forever.

**Comment by stingerbee12** [comment]
Okay thanks @graywolf336 (Good luck on the jail voting feature)

**Comment by stingerbee12** [comment]
Wait where can I download the latest build? Unless I already have it, I think.

**Comment by graywolf336** [comment]
Jail vote is finished :p

If you have update notifications enabled on the "dev" channel the plugin
will let you know when a new version is out with a URL.
