### ISSUE TITLE
Capitalized Jail Names Don't Exisit When Creating Cells

### ISSUE THREAD

**Issue by LigerXT5** [graywolf336/Jail#50]
http://i.gyazo.com/5a7b6a7aa4dcd1dbc94706611f268b4f.png

If a jail has a capital in the name, it cannot have cells. If you try to do "/jail createcell JailName," it says "jailname" does not exist.

Jail 3.0.0
Spigot 1.8.1 Build Number... Well, let's just say, /version states I'm only 4 builds behind, and I updated couple days ago.

**Comment by graywolf336** [comment]
Which build number? As that should have been fixed in build 168.

**Comment by LigerXT5** [comment]
[01:09:41] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-8a983f9-e81edfc (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[01:09:41] [Server thread/INFO]: You are 4 version(s) behind

This is all I know.

**Comment by graywolf336** [comment]
That's your Spigot version, not your jail version. You need to update your Jail plugin version, as that issue was fixed in Jail 3.0.0 Build 168.

**Comment by LigerXT5** [comment]
Uh, 3.0.0, the one listed on dev.bukket.org. There are no other builds listed for 3.0.0.
When I did /jail version, I got 3.0.0-SNAPSHOT-b139, so you are right, I need to update. I did not realize I had to update to a dev build to fix a release build bug on Jail. Sorry.

**Comment by graywolf336** [comment]
If you wait a few days, there will be another public release on Bukkit Dev which will contain the fix. It's going through testing now.
