### ISSUE TITLE
Add variable in message

### ISSUE THREAD

**Issue by Toshka17** [graywolf336/Jail#53]
Add to this message "broadcastmessageforminutes" variable "reason", please
it would be awesome)

And add variable "cell" :)

**Comment by graywolf336** [comment]
What do you mean add variable cell? Want a different message if they were jailed in a cell?

**Comment by Toshka17** [comment]
It would be perfect if the message "broadcastmessageforminutes" says not only about how many minutes player should be in a jail, but also in what prison, in what camera and for what reason.

Now it looks like this:
broadcastmessageforminutes: '&9% 0% has been jailed for %1% minutes.'

%0% - player, %1% - time.

And could be done as follows:
broadcastmessageforminutes: '&9%0% has been jailed for %1% minutes for %2% in %3% prison, in cell %4%.'

%0% - player, %1% - time, %2% - reason, %3% - jail_name, %4% - cell_name.

**Comment by graywolf336** [comment]
Problem is what if they're not jailed in a cell and are just jailed in that
jail? I'll have to add two messages to support them being jailed in cells.

**Comment by Toshka17** [comment]
hmmmm..

**Comment by graywolf336** [comment]
Actually, what I'll do is pass the information needed and you can add the numbers you described and they'll be there but it won't be in the default message.

**Comment by graywolf336** [comment]
`broadcastmessageforminutes`:
* `%0%` is the last known player name
* `%1%` is the length in minutes
* `%2%` is the reason
* `%3%` is the jail name
* `%4%` is the cell name, empty is no cell.

`broadcastmessageforever`:
* `%0%` is the last known player name
* `%1%` is the reason
* `%2%` is the jail name
* `%3%` is the cell name, empty is no cell.
