### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by Toshka17** [graywolf336/Jail#57]
There are such lines in the config.yml:
inventory:
blacklist: []
store: true
But if you put a value of "false", then the plugin will not save the inventory but will remove it when leaving the prison.

Is it possible to make the plugin do not save or delete the player's inventory when they are put in jail?
Because the plugin is often removes inventory because that is not compatible with other plugins, responsible for inventory.

**Comment by graywolf336** [comment]
I'm going to add an option to the config under inventory which will be `delete: true/false` so people can tell the plugin which route they want to go.

**Comment by graywolf336** [comment]
I take it back, I'm not going to add another configuration option. If storing inventory is set to false, then we won't clear their inventory upon them being unjailed.
