### ISSUE TITLE
Bug on Version Spigot version Build #20151203a 1.8 R0.1 (20141203)

### ISSUE THREAD

**Issue by NeoraxHD** [graywolf336/Jail#58]
I have an Problem with your Plugin everytime i Jail someone with this Command: (Name is example)
/jail Hallo123 -t 5 -j jail1 -c cell1 -m -r For Mining in the Build World
The Player is Jailed but on the Sign the Reason is not displayed!
My Plugins:
AutoMessage
ChatEx
Citizens
CommandBook
Hungergames
Jail
LogBlock
Multiverse-Core
OpenInv
ProtocoILib (idk what this is)
Repair
SignEdit (this is a plugin for editing signs idk if its the problem)
Spawner
SuperVanish
TalkAs
WGBlockRestricter
WGCustomFlags
WorldEdit
WorldGuard

That it is i hope you can fix my problem :)
Thanks

**Comment by graywolf336** [comment]
Which version of Jail? /version Jail

**Comment by NeoraxHD** [comment]
Jail v3.0.0 for 1.8.1

**Comment by graywolf336** [comment]
I need the build number.

**Comment by NeoraxHD** [comment]
Where i can read it out? 
Sorry but im not really good at this :)

**Comment by graywolf336** [comment]
Need to give me the full output of that command, should be something in
()'s.

**Comment by NeoraxHD** [comment]
Oh im Sorry i wrote shit im using the Version Jail-2.6.5-b3

**Comment by NeoraxHD** [comment]
There isnt any other information only:
Jail version 2.6.5-b3

**Comment by graywolf336** [comment]
You're using an old version which I don't support on this repository. When
i get back to my computer tomorrow I'll link you to more information.

**Comment by NeoraxHD** [comment]
Ok i will try installing the new Version

**Comment by graywolf336** [comment]
Please be aware, it is vastly different in command structure and
configuration.

**Comment by NeoraxHD** [comment]
Yea thanks............ my full config is now away and i dont even know how to make a Jail now... and the Commands at BukkitDev are outdated :-1:

**Comment by graywolf336** [comment]
Use the wiki on github.
