### ISSUE TITLE
Error loading Jail

### ISSUE THREAD

**Issue by thewjm2014** [graywolf336/Jail#59]
I am running Spigot 1.8 with Jail 3.0.0-snapshot-b182

I've successfully created a Jail and cells however when I reload jail I get the following error in console
"10.04 07:58:32 [Server] INFO Loaded 2 jail sticks.
10.04 07:58:30 [Server] INFO Loaded 0 prisoners.
10.04 07:58:30 [Server] INFO Loaded 24 cells.
10.04 07:58:30 [Server] INFO Loaded 1 jail.
10.04 07:58:30 [Server] INFO Loaded jail Jail with 0 prisoners and 24 cells.
>>>10.04 07:58:30 [Server] ERROR Failed to load the jail, Jailcells, because the world is not set.<<<
10.04 07:58:30 [Server] INFO Loaded the language: en"

I am unsure howto 'set' the world, in the data file it shows the following

I am also baffled by the signs: [] considering I placed signs and when I created the cells, I hit them with the wand and it now displays "empty cell" however in the data file I see signs: []

<<<<<<<<<<<<<<<<<<<<snip>>>>>>>>>>>>>>>>>>>>>>>
jails:
  Jailcells: {}
  Jail:
    world: CarlsWorld
    top:
      x: 54177
      y: 104
      z: 49673
    bottom:
      x: 54211
      y: 67
      z: 49737
    tps:
      in:
        x: 54206.57868335153
        y: 73.0
        z: 49705.931486459995
        yaw: 87.198364
        pitch: 38.249992
      free:
        world: CarlsWorld
        x: 54298.074003722075
        y: 71.0
        z: 49750.23288957271
        yaw: 261.19843
        pitch: 44.399986
    cells:
      cell_n8:
        tp:
          x: 54202.4171657459
          y: 81.0
          z: 49693.90105324754
          yaw: -11.800049
          pitch: 57.749954
        chest:
          x: 54199
          y: 81
          z: 49695
        signs: []
      cell_n9:
        tp:
          x: 54204.27100730521
          y: 81.0
          z: 49700.36349899019
          yaw: -276.54736
          pitch: 44.399956
        chest:
          x: 54199
          y: 81
          z: 49701
        signs: []
      cell_n23:
        tp:
          x: 54201.306597634924
          y: 88.0
          z: 49713.72374163673
          yaw: 29.59814
          pitch: 54.449974
        chest:
          x: 54197
          y: 88
          z: 49715
        signs: []
      cell_n4:
        tp:
          x: 54188.53790007957
          y: 81.0
          z: 49699.50700588866
          yaw: -4.895508
          pitch: 62.39988
        chest:
          x: 54191
          y: 81
          z: 49701
        signs: []
      cell_n15:
        tp:
          x: 54188.719681334696
          y: 88.0
          z: 49707.88380512103
          yaw: -0.8510742
          pitch: 65.69995
        chest:
          x: 54191
          y: 88
          z: 49709
        signs: []
      cell_n6:
        tp:
          x: 54187.275294413594
          y: 81.0
          z: 49686.999384681265
          yaw: -34.145996
          pitch: 39.449917
        chest:
          x: 54191
          y: 81
          z: 49689
        signs: []
      cell_n7:
        tp:
          x: 54203.46575832701
          y: 81.0
          z: 49688.910085483105
          yaw: -269.64868
          pitch: 64.49995
        chest:
          x: 54199
          y: 81
          z: 49689
        signs: []
      cell_n22:
        tp:
          x: 54201.33956169515
          y: 88.0
          z: 49708.07619087175
          yaw: -309.2518
          pitch: 58.649963
        chest:
          x: 54197
          y: 88
          z: 49709
        signs: []
      cell_n3:
        tp:
          x: 54188.750436247195
          y: 81.0
          z: 49706.07874991393
          yaw: -11.49292
          pitch: 69.14989
        chest:
          x: 54191
          y: 81
          z: 49707
        signs: []
      cell_n17:
        tp:
          x: 54188.68022869414
          y: 88.0
          z: 49695.83017546708
          yaw: -8.050049
          pitch: 66.449974
        chest:
          x: 54191
          y: 88
          z: 49696
        signs: []
      cell_n12:
        tp:
          x: 54202.42800605654
          y: 81.0
          z: 49719.85954011694
          yaw: -0.7010498
          pitch: 62.54996
        chest:
          x: 54199
          y: 81
          z: 49722
        signs: []
      cell_n18:
        tp:
          x: 54188.27446621714
          y: 88.0
          z: 49689.74995142261
          yaw: -14.500977
          pitch: 60.299976
        chest:
          x: 54191
          y: 88
          z: 49691
        signs: []
      cell_n13:
        tp:
          x: 54188.08007103781
          y: 88.0
          z: 49721.06285504991
          yaw: -130.90173
          pitch: 66.44996
        chest:
          x: 54191
          y: 88
          z: 49719
        signs: []
      cell_n24:
        tp:
          x: 54200.98220243763
          y: 88.0
          z: 49719.87327309339
          yaw: 27.198212
          pitch: 57.899937
        chest:
          x: 54197
          y: 88
          z: 49721
        signs: []
      cell_n19:
        tp:
          x: 54200.744391608656
          y: 88.0
          z: 49689.80175325874
          yaw: -346.0005
          pitch: 59.699978
        chest:
          x: 54197
          y: 88
          z: 49691
        signs: []
      cell_n10:
        tp:
          x: 54202.768354120264
          y: 81.0
          z: 49705.81631425398
          yaw: -351.5481
          pitch: 63.599976
        chest:
          x: 54199
          y: 81
          z: 49707
        signs: []
      cell_n14:
        tp:
          x: 54188.56719333903
          y: 88.0
          z: 49715.19146473498
          yaw: -177.70093
          pitch: 70.499954
        chest:
          x: 54191
          y: 88
          z: 49713
        signs: []
      cell_n11:
        tp:
          x: 54202.90088829855
          y: 81.0
          z: 49713.259638135125
          yaw: -333.24902
          pitch: 62.549984
        chest:
          x: 54199
          y: 81
          z: 49715
        signs: []
      cell_n5:
        tp:
          x: 54188.85424403714
          y: 81.0
          z: 49693.36438751881
          yaw: -350.94727
          pitch: 54.749886
        chest:
          x: 54191
          y: 81
          z: 49695
        signs: []
      cell_n16:
        tp:
          x: 54188.8314455299
          y: 88.0
          z: 49701.42620219696
          yaw: -351.54968
          pitch: 52.64994
        chest:
          x: 54191
          y: 88
          z: 49703
        signs: []
      cell_n21:
        tp:
          x: 54200.699274148225
          y: 88.0
          z: 49701.83589337634
          yaw: -1.3015137
          pitch: 64.19996
        chest:
          x: 54197
          y: 88
          z: 49703
        signs: []
      cell_n2:
        tp:
          x: 54188.60546746839
          y: 81.0
          z: 49712.74817719297
          yaw: -12.393555
          pitch: 62.699913
        chest:
          x: 54191
          y: 81
          z: 49714
        signs: []
      cell_n1:
        tp:
          x: 54187.2749247615
          y: 81.0
          z: 49719.69204780258
          yaw: -69.096436
          pitch: 50.099922
        chest:
          x: 54191
          y: 81
          z: 49721
        signs: []
      cell_n20:
        tp:
          x: 54200.61977876396
          y: 88.0
          z: 49695.66491403075
          yaw: -4.7512207
          pitch: 61.049957
        chest:
          x: 54197
          y: 88
          z: 49697
        signs: []
<<<<<<<<<<<<<<<<<</snip>>>>>>>>>>>>>>>>>>>>>>>>

anyways I hope you can help as I LOVE this plugin

**Comment by graywolf336** [comment]
What's the list of worlds you have on your server?

**Comment by thewjm2014** [comment]
At this stage my server only have one mine craft instance running 2
worlds.. Survival and pvp ..

**Comment by graywolf336** [comment]
Can you provide the name of the worlds? Just trying to figure out the root
of the issue

**Comment by thewjm2014** [comment]
Planet survivor is what I call my smp and planetsurvivirpvp is my pvp ..
Created using multiverse

**Comment by thewjm2014** [comment]
After running the setup script about 4 times all is good now
