### ISSUE TITLE
Problem deleting a jail/cells

### ISSUE THREAD

**Issue by Sharkykzn** [graywolf336/Jail#62]
Using the new commands. When wanting to delete a jail use /jail delete [jail] and get response to confirm with '/jail confirm'. When command is run get response - You are not confirming anything.
Same with trying to delete cells.

**Comment by Sharkykzn** [comment]
Status Update. I resorted to deleting information in my MySQl database and recreated the jails. Did not retry to delete jail or cells.

**Comment by graywolf336** [comment]
Which version are you using?
