### ISSUE TITLE
JailStick - Cell Bug

### ISSUE THREAD

**Issue by Dragon12dk** [graywolf336/Jail#68]
Hello, This is a very simple issue, but it is causing a lot of problems.
Basically what happens is if I Jail someone with a JailStick, Then for some reason they don't go to a cell, they just go to the jail spawn point...

**Comment by graywolf336** [comment]
Can you provide your jail sticks configuration and the full version you
have?

**Comment by Dragon12dk** [comment]
Ive got Jail v3.0.0 for 1.8.1

And my JailStick Config looks like this. It will send them to the jail for the right time, however they wont go into a cell.

jailstick:
  enabled: true
  sticks:
  - stick,10m,jail,Police,-1

**Comment by Dragon12dk** [comment]
Also I don't have any errors in the Console.

**Comment by graywolf336** [comment]
Can you provide the build number as well?

**Comment by Dragon12dk** [comment]
Jail v3.0.0 Beta 4 (build 182)

**Comment by graywolf336** [comment]
Looked into this and that's how the jail stick currently is designed. I'll add an option in the config to enable or disable the jail stick sending players to the first available cell it finds in the jail, defaulting it to enabled.

**Comment by Dragon12dk** [comment]
Ok. Thanks!

**Comment by Dragon12dk** [comment]
Hello, I noticed that you made a change to fix this issue. may I ask how to implement it into my config?
My normal config is here

jailstick:
  enabled: true
  sticks:
  - stick,10m,jail,Police,-1

How would I change it to send them to a random cell?

**Comment by graywolf336** [comment]
Just update to the newest build and that should be it, no configuration
changes required. :)

**Comment by Dragon12dk** [comment]
Ok, it seems to be a little strange for me. sometimes they go in a cell and sometimes they don't... do you maybe know what is causing this? 

My jail has over 25 cells, but if even one of the cells is taken, then no one else can use a cell, they are just brought to the spawn point of the prison.

**Comment by graywolf336** [comment]
Sounds like it believes your jail is full. Because what should happen is it tries to find an open cell and if one is found then jails someone there, but if none are found then it'll just place them into the jail's teleport in location. Using build 220, can you try to replicate it and then provide me steps to replicate the problem? This way we can figure out where the issue is coming from..

**Comment by Dragon12dk** [comment]
ah, Ok I sorted the problem out, The cells where all full of offline players. But I then ran into another issue, I got them in the cell but it says "Empty Cell" on the sign, is this already a known issue?

**Comment by graywolf336** [comment]
Don't know if I'd consider it a "bug" but an as is designed. The signs
don't get updated until they come online. But i can see where that'd be
confusing, if you want to open another issue about it I'll change that up
tomorrow. :)

**Comment by Dragon12dk** [comment]
ok, thanks!

**Comment by graywolf336** [comment]
Signs will now be updated as soon as someone is jailed in them, no matter if that someone is online or offline.
