### ISSUE TITLE
Sign refresh/verify commands

### ISSUE THREAD

**Issue by hitechwizard** [graywolf336/Jail#79]
When creating cells programmatically, it would be nice to have a command to refresh and verify all the signs.

Suggestion:  `/jail signs [verify|refresh] (cell_id)...(cell_id)`

Verify Methodology:  Iterate through all cells indicated (or all cells if none specified) and validate the blocks indicated by the config are actually signs, informing the player what cell/location is not a sign.

Refresh Methodology: Iterate through all cells indicated (or all cells if none specified) and reset the message that should be on the sign(s) for the specific cell (Empty Cell, or Prisoner time remaining)

**Comment by graywolf336** [comment]
:+1: will try to add it this week sometime.

**Comment by graywolf336** [comment]
Since different jails can have cells with the same name, I'm going to require a jail name before providing the list of cells to verify or refresh.

**Comment by hitechwizard** [comment]
Good catch.

**Comment by hitechwizard** [comment]
Works awesome!
![screen shot 2015-06-05 at 10 42 06 pm](https://cloud.githubusercontent.com/assets/1217502/8018197/49c25a00-0bd4-11e5-835f-224b5a5bd448.png)

**Comment by graywolf336** [comment]
:+1: a few of the changes I made actually allow for programmatically refreshing the signs as well and also added the ability for saving changes made to a cell which will allow for editing cells after they have been created, which doesn't exist currently and would be nice to have.
