### ISSUE TITLE
Cell names should be sorted alphabetically

### ISSUE THREAD

**Issue by hitechwizard** [graywolf336/Jail#80]
When a prison has lots of cells as in our Super Max prison, having the cells sorted would be nice instead of random order:
![screen shot 2015-06-02 at 9 59 00 pm](https://cloud.githubusercontent.com/assets/1217502/7951894/cb4a0974-0972-11e5-9592-9ff62a545585.png)

**Comment by graywolf336** [comment]
Should be sorted alphabetically now, but if you want to verify it that'd be great!

**Comment by hitechwizard** [comment]
Verified in 3.0.0-SNAPSHOT-b213
![screen shot 2015-06-03 at 12 10 34 am](https://cloud.githubusercontent.com/assets/1217502/7953069/fe239f2e-0984-11e5-9866-cff1c4409e73.png)

**Comment by graywolf336** [comment]
So, somewhat alphabetical. That good enough for what you was wanting?

**Comment by hitechwizard** [comment]
Its a string comparison vs. numeric comparison. I could have named the cells x0-x9 and been perfect, but at least each floor is together.

**Comment by Lolmaster25** [comment]
how do I change n to any other letter?
![image](https://cloud.githubusercontent.com/assets/22869447/21654155/9c486050-d2b4-11e6-9e12-2cc34e8c0bca.png)

**Comment by graywolf336** [comment]
@Lolmaster25 You have to provide the name of the cell when you're creating it.

**Comment by Lolmaster25** [comment]
The plugin doesn't ask for it, look at the images.

![image](https://cloud.githubusercontent.com/assets/22869447/21741394/52c91fc4-d4d4-11e6-95e3-3ff1ec9af06d.png)
![image](https://cloud.githubusercontent.com/assets/22869447/21741396/5f4be97a-d4d4-11e6-9b5a-fe0706feebfe.png)

**Comment by Lolmaster25** [comment]
Help, please... I can't continue setting my server without this plugin working.
