### ISSUE TITLE
Jail attempts to jail players that have never joined the server

### ISSUE THREAD

**Issue by hitechwizard** [graywolf336/Jail#82]
Using the /jail command, I seem to jail people like sign, etc. Before attempting to jail a player, jail should verify that the player has been on the server before.

The easiest way to check this is to use the Bukkit.OfflinePlayer.getLastPlayed(), which will return -1 if the player hasn't been on the server.

**Comment by graywolf336** [comment]
Couple ideas came to me from this.

First one is doing this but making it controllable via the config that way
if someone wanted that feature enabled it could be. Then if it is enabled
they have to type the confirm command to really jail someone who has never
been on before.

Second is command matching/suggestions. If you only provide one argument
then it suggests commands if it didn't find any.

**Comment by graywolf336** [comment]
Marking it as an enhancement since the old version of jail allowed for jailing players who had never visited the server before.

**Comment by graywolf336** [comment]
You can overwrite this with `-f` in the `/jail` command now.
