### ISSUE TITLE
Transferring prisoner does not update signs or indicate success

### ISSUE THREAD

**Issue by hitechwizard** [graywolf336/Jail#83]
Moving a prisoner from one cell to another within the same jail does not update the sign or indicate the transfer completed successfully. Moving a prisoner from one jail to different jail works as expected.

Assumption:  BadPlayer123 is a prisoner in the spawn jail in cell holding_1
Example:  ```/jail transfer -p badplayer123 -j spawn -c D_1```
Rreturns:  ```/jail transfer [-p player] (-j jail) (-c cell)```

The prisoner is transferred to cell D_1 according to /jail listcells, but requires a /jail signs update to get all the signs correct.

**Comment by graywolf336** [comment]
I will be taking a look at this later today, transferring code always
seemed dodgy to me and this just confirms my suspicions.
