### ISSUE TITLE
I can not create a prison help

### ISSUE THREAD

**Issue by zrtstr** [graywolf336/Jail#85]
I type in console
![1](https://cloud.githubusercontent.com/assets/13327267/8677003/bf6f4bc6-2a5d-11e5-8029-558123fc0c5c.jpg)

I receive an invitation
![2](https://cloud.githubusercontent.com/assets/13327267/8677022/d4bffaca-2a5d-11e5-9107-abe663d483dc.jpg)

I am trying to select a cube, a wooden sword clicking the left and right mouse button. Nothing happens. What do I do no wrong?

![3](https://cloud.githubusercontent.com/assets/13327267/8677060/0b6f1d30-2a5e-11e5-8e6f-682299b4532c.jpg)

**Comment by graywolf336** [comment]
Looks like you're left clicking (punching), you need to be right clicking.
Also, make sure no plugin is cancelling your actions such as
Vanish/VanishNoPacket or anything else.

**Comment by zrtstr** [comment]
Thanx Bro!! Im have gode mode. When im shutdown godmode (/ungod) everything work!!!! I have Jail!!!

**Comment by graywolf336** [comment]
Glad to hear, have fun! :)
