### ISSUE TITLE
I can not remove a prison

### ISSUE THREAD

**Issue by zrtstr** [graywolf336/Jail#86]
Hi bro! Its again me. I can not remove a prison. =((

im type /jail remove Jail
![1](https://cloud.githubusercontent.com/assets/13327267/8679488/f7571eac-2a6b-11e5-9d16-c22998b71a9d.jpg)

im type /jail confirm
![2](https://cloud.githubusercontent.com/assets/13327267/8679531/37f36ee8-2a6c-11e5-8cbf-0542b551d941.jpg)

What to do to remove the jail?

**Comment by graywolf336** [comment]
How long do you wait before you do that command? As after a little while it
expires, as a related note I need to update that message to say whatever
you was doing has expired.

**Comment by zrtstr** [comment]
I do this quickly. I do not wait

**Comment by zrtstr** [comment]
How i can delete jail? Its posible?

**Comment by graywolf336** [comment]
Try /jail delete <name> instead of remove, see if that works.

**Comment by zrtstr** [comment]
That's what I do. remove - is to remove the player from the prison .

**Comment by graywolf336** [comment]
I'm confused. What are you trying to do? What have you tried so far?

**Comment by zrtstr** [comment]
I do not properly set up the room. Now I try to remove the prison to re-create and configure properly .
/ jail stop
/ jail remove Jail
/ jail confirm

Not helps.

**Comment by zrtstr** [comment]
Maybe I delete a file somewhere ? The file where the data is recorded on the established prison . Or maybe remove the line in the file ?? Tell me how to remove it .

**Comment by graywolf336** [comment]
/jail delete <name>

and then

/jail confirm

**Comment by zrtstr** [comment]
not work. 
you are not confirming anything =((

**Comment by zrtstr** [comment]
you can come to my server and try if you want, im give you op. Ok?

**Comment by zrtstr** [comment]
im use Jail-3.0.0-SNAPSHOT

**Comment by zrtstr** [comment]
Jail-3.0.0-SNAPSHOT Feb 22, 2015

**Comment by zrtstr** [comment]
Bro I also can not remove the prisoners from the prison ahead of time.
/jail clear
/jail remove [name]
not work. Server answer - you are not confirming anything

**Comment by graywolf336** [comment]
Please post the results of: `/version Jail`

**Comment by zrtstr** [comment]
I had to remove the plug-in and restart the server so I could not release the player.
I downloaded the plugin from here http://dev.bukkit.org/bukkit-plugins/jail/files/ top line

**Comment by zrtstr** [comment]
Can I downloaded the wrong version ? Tell me the link to a working version for bukkit 1.8.7

**Comment by graywolf336** [comment]
Download the developer builds, you'll find the links in the readme of the project on here.

**Comment by zrtstr** [comment]
create please .jar file. I cant load surce in my server.

**Comment by graywolf336** [comment]
It's already created, please see the readme of this project.

**Comment by zrtstr** [comment]
http://ci.graywolf336.com/job/Jail/ from here? original-Jail-3.0.0-SNAPSHOT.jar this file?

**Comment by graywolf336** [comment]
No, the one which looks like the others you've used.
http://ci.graywolf336.com/job/Jail/lastSuccessfulBuild/artifact/target/Jail-3.0.0-SNAPSHOT.jar

**Comment by zrtstr** [comment]
THX! Now i try and write about this!

**Comment by zrtstr** [comment]
not work, version Jail-3.0.0 b237. Cant delete jail. you are not confirming anything

**Comment by zrtstr** [comment]
You have a cool plugin ! Please change it for the better!

**Comment by CheetahDrew** [comment]
Having the same issue not sure how to fix this as i'm trying to delete my jail but when I confirm it says i'm confirming nothing

**Comment by graywolf336** [comment]
Which version are you on, @CheetahDrew?

**Comment by graywolf336** [comment]
Are you guys using sqlite, mysql, or flatfile?
