### ISSUE TITLE
Punitive stone breaking

### ISSUE THREAD

**Issue by Deiscorides** [graywolf336/Jail#92]
Is there a way this can have a punitive stone breaking option? Example, "a player is jailed to a quarry area and must break X amount of Y block in order to be unjailed from the quarry area." Thus, chain gangs can be made for RP. The quarry area(s) can be reset via console/chat command, command block, and/or timer.

**Comment by graywolf336** [comment]
Currently, it kind of is but in a roundabout way. Enable jail pay and make it so they can pay with items. Then set the item to what you want people to do. Then whitelist the block break penalties for the blocks you want. They then can mine, pay for the jail via the items they pick up, and can get out. That make sense?

**Comment by Deiscorides** [comment]
Yeah, that will work. Thank you.

**Comment by graywolf336** [comment]
Let me know if you have any questions
