### ISSUE TITLE
v3.0.0 bug

### ISSUE THREAD

**Issue by Freakzor** [graywolf336/Jail#93]
There is no /jailcreate in that version, i cant even create a jail with that version ? 
Please add it and let us create jails with that version, becouse my server console is spamming There is new version v3.0.0 of Jail plugin, please update it. Non stop.... And when i put it i cant even create a jail with it thats why im using 1.7.4 version still working on 1.8.8 for me with correct configuration.. :)

**Comment by graywolf336** [comment]
Please read the description of the update. It explains everything about the
commands.
