### ISSUE TITLE
JailAPI null

### ISSUE THREAD

**Issue by OriginalsByToto** [graywolf336/Jail#94]
Hello, I'm a french server manager and I must create a plugin to jail players when he break or place block in prohibited zone, but the java command *jail = ((Jail) pl).API;* return a null JailAPI !

Is there a solution ?

Thank you in advance.

Here is my code : 
```java
           Plugin pl = getServer().getPluginManager().getPlugin("Jail");
			
		   if (pl != null)
		    {
		        jail = ((Jail) pl).API;
		    }
		    else
		    {
		    	getLogger().severe("Jail dependency not found !");
				pm.disablePlugin(this);
		    }
		    
		    if(jail == null) {
		    	
		    	getLogger().severe("Jail dependency not found !");
				pm.disablePlugin(this);
		    	
		    }
```

**Comment by graywolf336** [comment]
Are you using Jail 3 or Jail 2? If you're using Jail 3, it got updated to just [JailAPI](https://github.com/graywolf336/Jail/blob/master/src/main/java/com/graywolf336/jail/JailsAPI.java). For more information, see: https://github.com/graywolf336/Jail/wiki/api

**Comment by graywolf336** [comment]
For an example of how to use the API, take a look here: https://github.com/graywolf336/Jail/issues/72#issuecomment-104760384
