### ISSUE TITLE
Plz update to fix thesse bugs!

### ISSUE THREAD

**Issue by Fido2603** [graywolf336/Jail#97]
Hello graywolf!

On a server i play on we have some bugs... 
I do not have access to the console and soo on but here i will try to explain the bugs.

*Bug 1* 
When you get jailed and then gets unjailed(or just the time is done) then you sometimes loose your items...

*Bug 2*
The server i play on there is a survival world with the jail in and a creative world.
When players gets jailed when they are in the creative world then when they get out of the jail they will get their items from creative into the survival world!

*And btw. Is the plugin still active? It is 8 months since last uptate...*

**Comment by graywolf336** [comment]
Please verify the version used by the server is 3.0.0, as those sound like 2.x errors. Reopen this ticket with a screenshot of the version.
