### ISSUE TITLE
Jail record doesnt work

### ISSUE THREAD

**Issue by Verden1992** [graywolf336/Jail#99]
Hello,

we run the plugin with version 3.0.0-SNAPSHOT-b182 on spigot 1.8.8.

All works fine but one important thing anoying.

If you use /jail record [name] or /jail record [name], you get the message: [name] was 0 time jailed.

It doesnt matter if you use the command when the person is allready jailed, was jailed or if the person is on- or offline. This command doesnt work!

In plugin folder is a "record.yml". So there are records in that but they wont displayed ingame.

This is our config file:
http://pastebin.com/9mZyc3Lp

**Comment by graywolf336** [comment]
Try to update to one of the newer builds and let me know if you're still having problems. https://ci.craftyn.com/job/Jail/lastSuccessfulBuild/

**Comment by Verden1992** [comment]
Hello,

i updated the jail version. I turned the server offline, replace the jail version and deleted the records.yml. 
Then i jailed some persons and unjailed them. But /jail record allready not working.

But the plugin created a new records.yml with the records from the jailed persons.

And i found some new bugs with your version:
I cant use Tab to choose names anymore when i write /jail [name].
And when i try to use Tab with /jail check [name] i got all names of persons who are offline but allready jailed, so hundreds of names in an half year history, but not for the person who are online and jailed.

I have to type the name manually. Tab is brocken or what? :D

**Comment by graywolf336** [comment]
Open a different issue for the tab.

I'll look into the `/jail record` seemingly not working. Can you show me the exact command you're doing? Just so I can duplicate it.

**Comment by Verden1992** [comment]
First i jail someone with "/jail verden1992 -r test -t 10"

Then i unjail the Person with "/unjail verden1992"

Next step is: "/jail record verden1992" or "/jail record verden1992 list"

Both Commands give me the Feedback:
"Verden1992 was 0 times jailed"

But in the record.yml is a record about this. Who was jailed from which person, what time was it, date, how long and which reason.

I dont use mysql. So why the plugin dont read the record.yml?

If you want you can join our server to test it for yourself ^^

So for the the Bugs i shall create a New issue?

If you need any other Informations, ask me.

I will answer tomorrow in 7 hours. Here in germany its 00:02 :D

**Comment by Verden1992** [comment]
Hello? when i will get an answer?

**Comment by graywolf336** [comment]
When I get time to replicate it, whenever that is. Feel free to look into the issue and open a pull request to fix it. :smile:

**Comment by Verden1992** [comment]
ok, if you need any more information about my server, to replicate this issue, ask me :)

I dont know what you mean with that: 

 "Feel free to look into the issue and open a pull request to fix it. :smile:"

**Comment by Verden1992** [comment]
Hey whats up? :) any solution?
